import type { DiagramFormat } from "@/constants/diagram-formats";
import type { AppLocale } from "@/constants/i18n";
import type { ConversionReport } from "@/services/conversion/conversion-report";

export function buildConversionHeaderComment(
  report: ConversionReport,
  locale: AppLocale,
): string {
  const from = report.sourceFormat;
  const to = report.targetFormat;
  const losses = report.lossIds.join(", ");

  if (locale === "ru") {
    return [
      `' Сгенерировано конвертером vuePlantUML`,
      `' ${from} → ${to} (уровень ${report.level})`,
      `' Потери: ${losses}`,
    ].join("\n");
  }

  return [
    `' Generated by vuePlantUML converter`,
    `' ${from} → ${to} (level ${report.level})`,
    `' Losses: ${losses}`,
  ].join("\n");
}

export function buildMermaidConversionHeader(
  report: ConversionReport,
  locale: AppLocale,
): string {
  const comment = locale === "ru" ? "%%" : "%%";
  const header = buildConversionHeaderComment(report, locale)
    .split("\n")
    .map((line) => `${comment} ${line.replace(/^' /, "")}`)
    .join("\n");
  return header;
}

export function buildGraphmlConversionHeader(
  report: ConversionReport,
  locale: AppLocale,
): string {
  const header = buildConversionHeaderComment(report, locale)
    .split("\n")
    .map((line) => `<!-- ${line.replace(/^' /, "")} -->`)
    .join("\n");
  return header;
}

export function wrapConvertedSource(
  source: string,
  format: DiagramFormat,
  report: ConversionReport,
  locale: AppLocale,
): string {
  if (format === "mermaid") {
    return `${buildMermaidConversionHeader(report, locale)}\n${source}`;
  }

  if (format === "graphml") {
    return source.replace(
      /<\?xml[^>]*>\s*/,
      (match) => `${match}${buildGraphmlConversionHeader(report, locale)}\n`,
    );
  }

  if (source.startsWith("@start")) {
    return source.replace(
      /@start\w+/,
      (match) => `${match}\n${buildConversionHeaderComment(report, locale)}`,
    );
  }

  return `${buildConversionHeaderComment(report, locale)}\n${source}`;
}
